Traceback (most recent call last):
  File "model.py", line 42, in <module>
    combine_model.predict_shadow(mat_img)
  File "/content/DeepFaceDrawing/CombineModel.py", line 93, in predict_shadow
    sex=self.sex)
  File "/content/DeepFaceDrawing/models/AE_Model.py", line 94, in get_inter
    generated_f = self.get_latent(input_image)
  File "/content/DeepFaceDrawing/models/AE_Model.py", line 77, in get_latent
    mus_mouth = self.net_encoder(input_image)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/DeepFaceDrawing/models/networks.py", line 189, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/DeepFaceDrawing/models/networks.py", line 362, in forward
    ten = self.conv(ten)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 1, 4, 4], but got 3-dimensional input of size [1, 128, 128] instead